# Generated by Django 3.1.5 on 2021-11-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(db_column='quantite', default=1),
            preserve_default=False,
        ),
    ]
