# Generated by Django 3.1.5 on 2021-11-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(db_column='adresse', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
