# Generated by Django 3.1.5 on 2021-11-24 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateApprov', models.DateTimeField(auto_now=True, db_column='dateApprov')),
                ('quantite', models.FloatField(db_column='quantite')),
                ('refFss', models.ForeignKey(db_column='refFss', on_delete=django.db.models.deletion.CASCADE, to='api.fournisseur')),
                ('refProduit', models.ForeignKey(db_column='refProduit', on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
            options={
                'db_table': 'tbApprovisionnement',
            },
        ),
    ]
